"""
State definitions for the Report Draft Generator workflow.

This module defines TypedDict schemas for the unified pipeline that merges
report content generation and HTML design into a single workflow.

Schemas:
- ReportInput: User input structure (required + optional fields)
- TocItem: Table of Contents item structure
- ReportSection: Unified section for both generation and design phases
- DesignRequirement: HTML design settings (colors, orientation)
- DesignedPage: Final HTML output structure
- DraftGeneratorState: Main workflow state with reducers for parallel processing
"""

from __future__ import annotations

import operator
from typing import Annotated, Optional

from typing_extensions import NotRequired, TypedDict


class ReportInput(TypedDict, total=False):
    """
    User input schema for report generation.

    Required fields define the basic report structure.
    Optional fields enhance output quality.
    """

    # Required fields
    report_type: str
    """Report type: 주간업무보고, 기획안, 프로젝트 제안서, 결과 보고서, 회의록, etc."""

    purpose: str
    """Report purpose: 승인 요청, 현황 공유, 의사결정 요청, 아이디어 제안, etc."""

    audience: str
    """Target audience: 직속 상사, 임원, 타부서, 외부 클라이언트, etc."""

    topic: str
    """Report topic/title."""

    key_message: str
    """Core message or keywords to emphasize."""

    company_name: str
    """기업명 또는 조직명."""

    # Optional fields (for quality enhancement)
    company_info: NotRequired[str]
    """기업 설명 및 추가 정보."""
    tone: NotRequired[str]
    """Writing style: 격식체/반말, 간결함/상세함."""

    page_count: NotRequired[int]
    """Target number of pages (default: 3)."""

    emphasis: NotRequired[str]
    """Points to emphasize in the report."""

    include_visuals: NotRequired[bool]
    """Whether to include visual elements (charts, tables)."""

    additional_data: NotRequired[str]
    """Additional data or reference materials."""


class TocItem(TypedDict):
    """
    Table of Contents item structure.

    Generated by the TOC generation node based on user input.
    """

    page_id: str
    """Unique identifier matching ReportSection.page_id."""

    title: str
    """Section title."""

    description: str
    """Brief description of section contents (2-3 sentences)."""

    order: int
    """Section order in the report."""


class ReportSection(TypedDict):
    """
    Unified section structure for both generation and design phases.

    This schema bridges the gap between the generator's PageContent
    and the designer's Section types, serving both phases with a
    single data structure.
    """

    # Core fields (used by both phases)
    order: int
    """Sort order for report assembly."""

    page_id: str
    """Unique identifier (e.g., 'exec_summary', 'analysis')."""

    title: str
    """Section title."""

    content: str
    """Markdown content (A4 page-appropriate, 800-1200 chars for Korean)."""

    # Designer-specific fields (auto-populated during generation)
    section_title: str
    """Display title for the section (same as title)."""

    section_number: Optional[str]
    """Section number (e.g., '1.0', '2.0')."""

    section_key: str
    """Layout key (uppercase page_id, e.g., 'EXECUTIVE_SUMMARY')."""

    parent_path: Optional[str]
    """Breadcrumb path for nested sections."""


class DesignRequirement(TypedDict):
    """
    Design settings for HTML generation.

    Controls colors and PDF orientation for the final output.
    """

    primary_color: str
    """Primary brand color (e.g., '#1E40AF')."""

    secondary_color: str
    """Secondary color (e.g., '#3B82F6')."""

    accent_color: str
    """Accent/highlight color (e.g., '#10B981')."""

    pdf_orientation: str
    """PDF orientation: 'portrait' or 'landscape'."""


# Default design requirement for standalone usage
DEFAULT_DESIGN_REQUIREMENT: DesignRequirement = {
    "primary_color": "#1E40AF",
    "secondary_color": "#3B82F6",
    "accent_color": "#10B981",
    "pdf_orientation": "portrait",
}


class DesignedPage(TypedDict):
    """
    Individual designed page structure.

    Each page is generated in parallel by the design_section node
    and combined into the final output.
    """

    html_content: str
    """Designed HTML content for PDF rendering."""

    order: int
    """Sort order for final assembly."""

    section_title: str
    """Section title for reference."""

    section_number: Optional[str]
    """Section number."""

    outline_id: str
    """Reference ID for the outline."""

    page_index: int
    """Page index within multi-page sections (0 for single-page)."""

    model_used: Optional[str]
    """LLM model used to generate this page."""


class DraftGeneratorState(TypedDict):
    """
    Unified workflow state for the Report Draft Generator.

    Combines report generation and HTML design phases into a single
    state machine. Uses operator.add reducers for parallel processing
    of sections and designed pages.
    """

    # Input
    input: ReportInput
    """User input for report generation."""

    # Phase 1: Content Generation
    toc: list[TocItem]
    """Generated TOC items."""

    sections: Annotated[list[ReportSection], operator.add]
    """
    Generated sections with content.

    Uses operator.add reducer to aggregate results from parallel
    page generation. Each node returns a single-item list.
    """

    # Phase 2: HTML Design
    design_requirement: DesignRequirement
    """Design settings (colors, orientation)."""

    designed_pages: Annotated[list[DesignedPage], operator.add]
    """
    Designed HTML pages.

    Uses operator.add reducer to aggregate results from parallel
    section design. Each node returns a single-item list (or more
    for multi-page sections).
    """

    # Output
    final_html: Optional[str]
    """Combined final HTML output (optional)."""

    # Metadata
    status: str
    """Current workflow status."""

    errors: Annotated[list[str], operator.add]
    """Error messages collected during execution."""


class PageGenerationPayload(TypedDict):
    """
    Payload for Send() API in parallel page content generation.

    Passed to generate_page_content node via Send().
    """

    page_info: TocItem
    """TOC item containing page metadata."""

    user_input: ReportInput
    """Original user input for context."""


class DesignSectionPayload(TypedDict):
    """
    Payload for Send() API in parallel section design.

    Passed to design_section node via Send().
    """

    section: ReportSection
    """Section to design."""

    design_requirement: DesignRequirement
    """Design settings."""

    language_code: str
    """Language code for prompts (default: 'ko')."""

    outline_id: str
    """Outline ID for reference."""
